// FILE: src/lib/api-schema.d.ts

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/register": {
    post: {
      summary: "Register user";
      requestBody: {
        content: {
          "application/json": {
            email: string;
            phone?: string;
            password: string;
            tenant_slug?: string;
          };
        };
      };
      responses: {
        /** @description Registered */
        201: {
          content: never;
        };
      };
    };
  };
  "/auth/login": {
    post: {
      summary: "Login";
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthLoginReq"];
        };
      };
      responses: {
        /** @description JWT + refresh token */
        200: {
          content: {
            "application/json": components["schemas"]["AuthLoginRes"];
          };
        };
      };
    };
  };
  "/tenants": {
    post: {
      summary: "Create tenant (business)";
      requestBody: {
        content: {
          "application/json": components["schemas"]["TenantCreateReq"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["TenantRes"];
          };
        };
      };
    };
  };
  "/tenants/{tenantId}/services": {
    get: {
      summary: "List services (public or RBAC-filtered)";
      parameters: {
        path: {
          tenantId: components["schemas"]["UUID"];
        };
      };
      responses: {
        /** @description List of services */
        200: {
          content: {
            "application/json": components["schemas"]["ServiceRes"][];
          };
        };
      };
    };
    post: {
      summary: "Create service (admin)";
      parameters: {
        path: {
          tenantId: components["schemas"]["UUID"];
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ServiceReq"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UUID: string;
    AuthLoginReq: {
      email: string;
      password: string;
    };
    AuthLoginRes: {
      access_token?: string;
      refresh_token?: string;
      expires_in?: number;
    };
    TenantCreateReq: {
      name: string;
      slug: string;
      timezone?: string;
      currency?: string;
    };
    TenantRes: {
      id?: components["schemas"]["UUID"];
      name?: string;
      slug?: string;
      branding?: {
        [key: string]: unknown;
      };
    };
    ServiceReq: {
      name: string;
      /** @description appointment | rental | service */
      type: string;
      duration_minutes?: number;
      price_cents?: number;
      capacity?: number;
      metadata?: {
        [key: string]: unknown;
      };
    };
    ServiceRes: {
      id?: components["schemas"]["UUID"];
      tenant_id?: components["schemas"]["UUID"];
      name?: string;
      type?: string;
      duration_minutes?: number;
      price_cents?: number;
      capacity?: number;
      active?: boolean;
    };
    // Add other schemas as needed...
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;